### ISSUE TITLE
Question about triple numbers of datasets.

### ISSUE THREAD

**Issue by LiuYuLOL** [thunlp/explore-and-evaluate#3]
Hi, thanks for the great work.

I'm not so sure but I find the real triple numbers of datasets are different from the paper reported. For example, DBP15k/zh contains rel-triples: 70414, char-facts: 182991, and dig-facts: 86184 with the following code:
```
print('rel-facts:', len(self.loaded_data.triples_sr), len(self.loaded_data.triples_tg))
print('char-facts:', len(self.loaded_data.literal_triples_sr), len(self.loaded_data.literal_triples_tg))
print('dig-facts:', len(self.loaded_data.digital_triples_sr), len(self.loaded_data.digital_triples_tg))
```

Thanks again.

**Comment by acharkq** [comment]
Thank you for pointing out this issue!

I have updated in arXiv version.

**Comment by Zyjacya-In-love** [comment]
Hi, thanks for the great work.

I have some questions during reading your paper and code. For DBP15k/zh that JAPE provided, I found 153K rel-triples, but the DBP15K that get from your OneDrive, I just found 70k rel-triples. Why and How change the number of rel-triples?

Thanks again.

**Comment by acharkq** [comment]
Can you check if the relation tripes in JAPE have duplicates of the reversed direction?

**Comment by Zyjacya-In-love** [comment]
Oh, sorry, i may make a mistake. 

I get the DBP15k from [http://ws.nju.edu.cn/jape/](http://ws.nju.edu.cn/jape/) earlier, there are 150k rel-triples in it. And you may get DBP15k from JAPE's github data folder, there are 70k rel-triples in it. 

further, i found the describe from [JAPE's github](https://github.com/nju-websoft/JAPE) that 
>Datasets
In our experiment, we do not use all the triples in datasets. For relationship triples, we select a portion whose head and tail entities are popular. For attribute triples, we discard their values due to diversity and cross-linguality.
>
>The whole datasets can be found [here](http://ws.nju.edu.cn/jape/).

So 150k rel-triples may be all the triples in datasets, and the 70k rel-triples was selected by JAPE.

Finally, I'm very interested in your work. And there are some differences between the dataset you provided and [JAPE's github](https://github.com/nju-websoft/JAPE). Could you push or send me(ziqiangxu97@gmail.com) the code of the data processing?

Thanks a lot.

**Comment by acharkq** [comment]
Hi @Zyjacya-In-love,

The major difference between our used DBP15k and the one in JAPE's github is that we include attribute triples from the DBpedia dump (2016-10). All other parts are the same.
